name: codecrafters-redis
version: 0.1.0.0
license: BSD3


default-extensions:
  - OverloadedStrings
  - BangPatterns
  - ViewPatterns
  - DeriveGeneric
  - DeriveAnyClass
  - ScopedTypeVariables
  - NumericUnderscores
  - LambdaCase
  

ghc-options:
  - -Wall
  - -threaded

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
  - network-simple # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - network # required when using bytestring
  - text # use Text rather than String
  - stm # may help with a concurrent database
  - stm-containers
  - containers # may help with the database structure and debugging
  - time # may help with the expiry function
  - async # may help with concurrency
  - mtl # may help with structuring
  - optparse-applicative

library:
  source-dirs: src
  dependencies:
    - megaparsec
    - parser-combinators
    - parsec
    - attoparsec

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-redis
    ghc-options:
      - -rtsopts         # разрешаем RTS-флаги
      - -with-rtsopts=-N # по умолчанию использовать все ядра

tests:
  protocol-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
    - codecrafters-redis
    - QuickCheck
