name: codecrafters-redis
version: 0.1.0.0
license: BSD3


default-extensions:
  - OverloadedStrings
  - BangPatterns

ghc-options:
  - -Wall
  - -threaded

dependencies:
  - base >= 4.19 && < 5
  - network-simple # establish a simple TCP network
  - bytestring # useful to send bytes over the network
  - network # required when using bytestring
  - text # use Text rather than String
  - stm # may help with a concurrent database
  - stm-containers
  - containers # may help with the database structure and debugging
  - time # may help with the expiry function
  - async # may help with concurrency
  - mtl # may help with structuring
  # Parsing libs
  - megaparsec
  - parser-combinators
  - parsec
  - attoparsec

library:
  source-dirs: src
  dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)

executables:
  codecrafters-redis-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - codecrafters-redis
    ghc-options:
      - -rtsopts         # разрешаем RTS-флаги
      - -with-rtsopts=-N # по умолчанию использовать все ядра
